# Generated by Django 5.2.12 on 2026-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='activity_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
