# Generated by Django 5.2.12 on 2026-03-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0002_schedule_activity_description_schedule_is_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
