# Generated by Django 5.2.12 on 2026-03-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0004_schedule_user_alter_schedule_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='giver',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skillshare.skill'),
        ),
    ]
