# Generated by Django 5.2.12 on 2026-03-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0005_remove_skill_giver_customuser_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='giver',
        ),
    ]
