# Generated by Django 5.2.12 on 2026-03-13 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0006_rename_user_schedule_giver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
