# Generated by Django 5.2.12 on 2026-03-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0007_alter_schedule_giver'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de jours de disponibilité', null=True),
        ),
    ]
