@startuml

class User{
    + Standard Django User fields
    + slug
}

class Skill {
    + id : int
    + name: str
    + category : Category
    + giver : User
    + activity_description : str
    + is_request : bool
}

class Category {
    + id : int
    + name: str
    + description : str
}

class Schedule {
    + id : int
    + skill : Skill
    + scheduled_at : DateTime
    + is_active : bool 
    + taker : User | None
}

Skill "1" -- "1..*" Category

User "1" -- "0..*" Skill

Schedule "1..*" -- "1" Skill