@startuml
left to right direction
skinparam packageStyle rectangle
actor Visiteur
actor User
actor Admin
rectangle SkillShare {
    Visiteur -- (Affiche les prochains créneaux anonymement)
    Visiteur -- (Affiche la liste des compétences proposées)
    User -- (Indiquer les compétences qu'il possède et peut partager)
    User -- (Indiquer les créneaux où il recherche de l'aide pour une compétence non possédée)
    User -- (Afficher les créneaux où d'autres utilisateurs recherchent une compétence qu'il possède)
    User -- (Réserver un créneau pour aider un autre utilisateur)
    Admin -- (Gestion des utilisateurs et des droits)
    Admin -- (Visualisation de tous les créneaux et utilisateurs)
}
@enduml